<?php

namespace Container3XPAIC1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BhddMx4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BhddMx4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BhddMx4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\addParksController::insert' => ['privates', '.service_locator.hFU0vWd', 'get_ServiceLocator_HFU0vWdService', true],
            'App\\Controller\\parksController::homepage' => ['privates', '.service_locator.4kydGdO', 'get_ServiceLocator_4kydGdOService', true],
            'App\\Controller\\parksController::showPark' => ['privates', '.service_locator.P29ujsq', 'get_ServiceLocator_P29ujsqService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\addParksController:insert' => ['privates', '.service_locator.hFU0vWd', 'get_ServiceLocator_HFU0vWdService', true],
            'App\\Controller\\parksController:homepage' => ['privates', '.service_locator.4kydGdO', 'get_ServiceLocator_4kydGdOService', true],
            'App\\Controller\\parksController:showPark' => ['privates', '.service_locator.P29ujsq', 'get_ServiceLocator_P29ujsqService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\addParksController::insert' => '?',
            'App\\Controller\\parksController::homepage' => '?',
            'App\\Controller\\parksController::showPark' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\addParksController:insert' => '?',
            'App\\Controller\\parksController:homepage' => '?',
            'App\\Controller\\parksController:showPark' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
