<?php

namespace Container3XPAIC1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParkServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\parkService' shared autowired service.
     *
     * @return \App\Service\parkService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/parkService.php';

        return $container->privates['App\\Service\\parkService'] = new \App\Service\parkService(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()), ($container->services['cache.app'] ?? $container->getCache_AppService()));
    }
}
