<?php

namespace ContainerKwHObGz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P29ujsqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P29ujsq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P29ujsq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\ParksRepository', 'getParksRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\ParksRepository',
        ]);
    }
}
