<?php

namespace ContainerKwHObGz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HFU0vWdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hFU0vWd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hFU0vWd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'arrayparques' => ['privates', 'App\\Service\\parkService', 'getParkServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'arrayparques' => 'App\\Service\\parkService',
            'entityManager' => '?',
        ]);
    }
}
