<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKwHObGz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKwHObGz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKwHObGz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKwHObGz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKwHObGz\App_KernelDevDebugContainer([
    'container.build_hash' => 'KwHObGz',
    'container.build_id' => '503f6d92',
    'container.build_time' => 1678395436,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKwHObGz');
